import { loadState } from './persistence.js';

// Function to create a default state for a single schema
export function createDefaultSchemaState() {
    return {
        title: 'New Schema',
        description: 'A schema generated by the JSON Schema Builder',
        rootSchemaType: 'object',
        schemaDefinition: [],
        definitions: [],
        nextId: 0,
    };
}

const initialState = {
    schemas: [createDefaultSchemaState()],
    activeSchemaIndex: 0,
    draggedItemId: null,
};

const loadedState = loadState();

export let appState = {
    ...initialState,
    ...loadedState, // Overwrite defaults with any saved state.
};

// Getter for the active schema's state
export function getActiveSchemaState() {
    if (!appState.schemas || appState.schemas.length === 0) {
        // This is a fallback, should ideally not be reached if state is managed properly
        appState.schemas = [createDefaultSchemaState()];
        appState.activeSchemaIndex = 0;
    }
    return appState.schemas[appState.activeSchemaIndex];
}
