import { loadState } from './persistence.js';

const initialState = {
    rootSchemaType: 'object',
    title: 'Generated Schema',
    description: 'A schema generated by the JSON Schema Builder',
    definitions: [], // For $defs
    schemaDefinition: [], // For root properties/items
    nextId: 0,
    draggedItemId: null,
};

const loadedState = loadState();

export let appState = {
    ...initialState,
    ...loadedState, // Overwrite defaults with any saved state.
};
